### PR TITLE
`nflreadr::nflverse_game_id()` accepts old team abbreviations

### LINKED ISSUE #190: `nflverse_game_id` rejects abbreviations too aggressive and outputs bad error message
``` r
away_teams <- c("LA", "LA", "LAR", "SD")
home_teams <- c("KC", "KC", "KC", "KC")
nflreadr::nflverse_game_id(2022, 2, away_teams, home_teams)
#> Error in `nflreadr::nflverse_game_id()`:
#> ! "LA", "LA", "LAR", and "SD" is not a valid `away` abbreviation.
#> Backtrace:
#>     ▆
#>  1. └─nflreadr::nflverse_game_id(2022, 2, away_teams, home_teams)
#>  2.   └─cli::cli_abort("{.val {away}} is not a valid {.arg away} abbreviation.")
#>  3.     └─rlang::abort(...)
```

`SD` is a valid (but old) team abbreviation and the error messages prints the complete input vector instead of the rejected abbreviation

### PR DESCRIPTION
**Pull request by mrcaseb**
and outputs useful errors

closes #190

### CODE REVIEW

**Review by tanho63 — COMMENTED** [review]
Can you add a testthat line that captures the new behaviour?

**Comment by mrcaseb** [comment]
Seems like `rlang::check_installed("qs")` is failing in Mac OS. Not sure what's going on.

**Review by tanho63 — APPROVED** [review]
LGTM

**Comment by tanho63** [comment]
I've set the required checks to ubuntu 22.04 release and devel for now, will turn mac/windows back on before cran release

**Pull request merged**
