### PR TITLE
use data.table::fifelse and call it a day

### LINKED ISSUE #213: [BUG] nflreadr:::join_coalesce() converts dates to ints when joining
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

1.3.2.11

### Describe the bug

The internal function `nflreadr:::join_coalesce()` converts date objects to integers when joining.

### Reprex

```r
df1 <- data.frame(
  name = c("Tom",
           "Bill",
           "Jen"),
  birth_date = c("1998-05-01",
                 "1997-12-12",
                 NA_character_)
) |>
  dplyr::mutate(birth_date = lubridate::as_date(birth_date))

df2 <- data.frame(
  name = c("Jen",
           "Tom",
           "Bill"),
  birth_date = c("1995-01-31",
                 NA_character_,
                 "1997-12-12")
) |>
  dplyr::mutate(birth_date = lubridate::as_date(birth_date))

nflreadr:::join_coalesce(
  df1,
  df2,
  by=c("name")
)
#>    name birth_date
#> 1: Bill      10207
#> 2:  Jen       9161
#> 3:  Tom      10347
```

### Expected Behavior

The object returned by `nflreadr:::join_coalesce()` should instead look like:

```r
#>   name birth_date
#> 1  Tom 1998-05-01
#> 2 Bill 1997-12-12
#> 3  Jen 1995-01-31
```

### nflverse_sitrep

```r
── System Info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• R version 4.3.1 (2023-06-16 ucrt)   • Running under: Windows 11 x64 (build 22000)
── nflverse Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• nflreadr (1.3.2.11)    • nflseedR (1.2.0)  • nflplotR (1.1.0.9006)  
• nflfastR (4.5.1.9009)  • nfl4th   (1.0.4)  • nflverse (1.0.3)       
── nflverse Options ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• nflreadr.verbose: FALSE
── nflverse Dependencies ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• askpass     (1.1)     • hms        (1.1.3)    • proto        (1.0.0)    
• backports   (1.4.1)   • httr       (1.4.6)    • purrr        (1.0.1)    
• cachem      (1.0.8)   • isoband    (0.2.7)    • R6           (2.5.1)    
• cli         (3.6.1)   • janitor    (2.2.0)    • rappdirs     (0.3.3)    
• codetools   (0.2-19)  • jsonlite   (1.8.7)    • RColorBrewer (1.1-3)    
• colorspace  (2.1-0)   • labeling   (0.4.2)    • Rcpp         (1.0.11)   
• cpp11       (0.4.6)   • lattice    (0.21-8)   • rlang        (1.1.1)    
• crayon      (1.5.2)   • lifecycle  (1.0.3)    • rstudioapi   (0.15.0)   
• curl        (5.0.1)   • listenv    (0.9.0)    • scales       (1.2.1)    
• data.table  (1.14.8)  • lubridate  (1.9.2)    • snakecase    (0.11.0)   
• digest      (0.6.33)  • magick     (2.7.5)    • stringi      (1.7.12)   
• dplyr       (1.1.2)   • magrittr   (2.0.3)    • stringr      (1.5.0)    
• fansi       (1.0.4)   • MASS       (7.3-60)   • sys          (3.4.2)    
• farver      (2.1.1)   • Matrix     (1.6-0)    • tibble       (3.2.1)    
• fastmap     (1.1.1)   • memoise    (2.0.1)    • tidyr        (1.3.0)    
• fastrmodels (1.0.2)   • mgcv       (1.8-42)   • tidyselect   (1.2.0)    
• furrr       (0.3.1)   • mime       (0.12)     • timechange   (0.2.0)    
• future      (1.33.0)  • munsell    (0.5.0)    • utf8         (1.2.3)    
• generics    (0.1.3)   • nlme       (3.1-162)  • vctrs        (0.6.3)    
• ggplot2     (3.4.2)   • openssl    (2.1.0)    • viridisLite  (0.4.2)    
• globals     (0.16.2)  • parallelly (1.36.0)   • withr        (2.5.0)    
• glue        (1.6.2)   • pillar     (1.9.0)    • xgboost      (2.0.0.1)  
• gsubfn      (0.7)     • pkgconfig  (2.0.3)      
• gtable      (0.3.3)   • progressr  (0.13.0)     
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mrcaseb**
fixes #213 

``` r
`%c%` <- nflreadr:::`%c%`
d1 <- lubridate::as_date(c("1998-05-01",
                           "1997-12-12",
                           NA_character_))
d2 <- lubridate::as_date(c("1995-01-31",
                           NA_character_,
                           "1997-12-12"))
d1 %c% d2
#> [1] "1998-05-01" "1997-12-12" "1997-12-12"

d3 <- as.Date(c("1998-05-01",
                "1997-12-12",
                NA_character_))
d4 <- as.Date(c("1995-01-31",
                NA_character_,
                "1997-12-12"))
d3 %c% d4
#> [1] "1998-05-01" "1997-12-12" "1997-12-12"
```

### CODE REVIEW

**Comment by mrcaseb** [comment]
various tests failing because we are in September without an NFL game being played yet

**Comment by tanho63** [comment]
Will wait on whether the CRAN submission succeeds or fails before merging, currently in limbo.

**Comment by tanho63** [comment]
also just broadly laughing that my mind went to vctrs first instead of checking the datatable ifelse first lol

**Review by tanho63 — APPROVED** [review]
LGTM

**Pull request merged**
