### PR TITLE
Add ps kicking

### PR DESCRIPTION
**Pull request by tanho63**

### CODE REVIEW

**Comment by tanho63** [comment]
had initially added rlang arg_match but I think I prefer the "remove dplyr/purrr dependency" route personally

**Comment by tanho63** [comment]
it should work cleanly to merge this then #38 but you can also close this and just merge 38 🤷‍♂️

**Review by mrcaseb — APPROVED** [review]
lgtm

**Comment by mrcaseb** [comment]
> 
> 
> had initially added rlang arg_match but I think I prefer the "remove dplyr/purrr dependency" route personally, esp if we can go the data.table route instead and stay in the same areacode speedwise

removing dplyr/purrr dependency is a good idea imo. But since cachem and memoise depend on rlang directly we can still use it here. I'll probably do this in another PR

``` r
tools::package_dependencies(c("cachem", "data.table", "curl", "memoise", "qs", "rappdirs"), recursive = TRUE)
#> $cachem
#> [1] "rlang"   "fastmap" "utils"  
#> 
#> $data.table
#> [1] "methods"
#> 
#> $curl
#> character(0)
#> 
#> $memoise
#> [1] "rlang"   "cachem"  "fastmap" "utils"  
#> 
#> $qs
#> [1] "Rcpp"          "RApiSerialize" "stringfish"    "methods"      
#> [5] "utils"         "RcppParallel" 
#> 
#> $rappdirs
#> character(0)
```

**Pull request merged**
