### PR TITLE
add hive-style partitioning to `download_nflverse()`

### LINKED ISSUE #124: add hive style folders for `download_nflverse`
For optimal “arrow” compatibility, hive style season subfolders would make things more efficient to read as a file system dataset. https://arrow.apache.org/docs/r/reference/open_dataset.html

sketching:

-  use_hive as default if file type in parquet or csv
- use gsub to make the file paths and fs to do the renaming

### PR DESCRIPTION
**Pull request by tanho63**
Should resolve #124 - this one's for @jthomasmock :grinning: 

example usage:
```r
# pak::pak("nflverse/nflreadr@hive")
library(nflreadr)

download_nflverse("snap_counts", file_type = "parquet", folder_path = "dev")

fs::dir_tree("dev")

arrow::open_dataset("dev/snap_counts")
```
```r
R> download_nflverse("snap_counts", file_type = "parquet", .... [TRUNCATED] 
ℹ Now downloading 10 files to dev.
ℹ Downloading "snap_counts_2012.parquet"...
  |=========================================================| 100%
ℹ Downloading "snap_counts_2013.parquet"...
  |=========================================================| 100%
ℹ Downloading "snap_counts_2014.parquet"...
  |=========================================================| 100%
ℹ Downloading "snap_counts_2015.parquet"...
  |=========================================================| 100%
ℹ Downloading "snap_counts_2016.parquet"...
  |=========================================================| 100%
ℹ Downloading "snap_counts_2017.parquet"...
  |=========================================================| 100%
ℹ Downloading "snap_counts_2018.parquet"...
  |=========================================================| 100%
ℹ Downloading "snap_counts_2019.parquet"...
  |=========================================================| 100%
ℹ Downloading "snap_counts_2020.parquet"...
  |=========================================================| 100%
ℹ Downloading "snap_counts_2021.parquet"...
  |=========================================================| 100%
✔ Downloaded 10 files to dev.

R> fs::dir_tree("dev")
dev
└── snap_counts
    ├── season_=2012
    │   └── snap_counts_2012.parquet
    ├── season_=2013
    │   └── snap_counts_2013.parquet
    ├── season_=2014
    │   └── snap_counts_2014.parquet
    ├── season_=2015
    │   └── snap_counts_2015.parquet
    ├── season_=2016
    │   └── snap_counts_2016.parquet
    ├── season_=2017
    │   └── snap_counts_2017.parquet
    ├── season_=2018
    │   └── snap_counts_2018.parquet
    ├── season_=2019
    │   └── snap_counts_2019.parquet
    ├── season_=2020
    │   └── snap_counts_2020.parquet
    └── season_=2021
        └── snap_counts_2021.parquet

R> arrow::open_dataset("dev/snap_counts")
FileSystemDataset with 10 Parquet files
game_id: string
pfr_game_id: string
season: int32
game_type: string
week: int32
player: string
pfr_player_id: string
position: string
team: string
opponent: string
offense_snaps: double
offense_pct: double
defense_snaps: double
defense_pct: double
st_snaps: double
st_pct: double
season_: int32

See $metadata for additional Schema metadata
```

~~There were some column-type/namespace collisions between "season" within the dataframe and with the partitioning - some files (e.g. rosters, pbp etc) are marked as doubles rather than ints which causes open_dataset to break. That's why `season_` is suffixed with a `_` - to prevent collisions~~

### CODE REVIEW

**Comment by jthomasmock** [comment]
> There were some column-type/namespace collisions between "season" within the dataframe and with the partitioning - some files (e.g. rosters, pbp etc) are marked as doubles rather than ints which causes open_dataset to break. That's why season_ is suffixed with a _ - to prevent collisions

I've been frustrated by this before - we probably need to back-port standardized types across seasons. I get why you're doing this to avoid a collision, but I'm not sure if something like `filter(season)` works properly? 

Need to test but I'm leaning towards let's standardize the col type of `season` over adjusting the hive name.

**Comment by tanho63** [comment]
> need to back-port standardized types across seasons

yeah, this might be the nudge to go back and coerce it all to ints. for at least season and week across everything. I wonder if I can make a lazy wrapper outside of the dataframes themselves....

**Review by mrcaseb — APPROVED** [review]
Looks good to me. We might want to fix this NOTE in this PR as well since we are not far away from a CRAN release

```
❯ checking dependencies in R code ... NOTE
[103](https://github.com/nflverse/nflreadr/runs/7670491532?check_suite_focus=true#step:6:104)
  Namespace in Imports field not imported from: 'methods'
    All declared Imports should be used.
```

**Comment by mrcaseb** [comment]
> 

I agree with Tom here. If the current implementation would force us to do `group_by(season_)` instead of `group_by(season)` it is definitely worth going into the data scripts and forcing season to be integer/double

**Comment by tanho63** [comment]
@jthomasmock did some poking around, it looks like pbp works with the season/week as-is, so I'm good with just rolling with season as the partition name and then will go through and fix the nflverse-data releases individually. 

@mrcaseb have imported setOldClass to silence note

**Review by mrcaseb — APPROVED** [review]
Lgtm

**Pull request merged**
